name: NPM Compile

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main", \
                "testing", \
                "publish" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: build
        run: |
          cd code
          npm install
          npm run build
      - name: archive npm artefacts
        uses: actions/upload-artifact@v3
        with:
          name: dis
          path: |
            public/build/assets

      - name: archive npm lockfile
        uses: actions/upload-artifact@v3
        with:
          name: save npm lockfile
          path: |
            *-lock.json
