name: 'Dependency Review'
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main", "development", "testing", "publish"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2