name: Laravel Testing
on:
  push:
    branches: [ "main", \
                "development" ]

  pull_request:
    branches: [ "main", \
                "testing", \
                "development" ]


jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      # Setup of PHP
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
          extensions: intl, BCMath, ctype, fileinfo, OpenSSL, pdo_mysql, tokenizer
          tools: composer, phpunit, pecl, phpize

      # Base setup
      - uses: actions/checkout@v3

      # Caching
      ## PHP - cache
      - name: cache vendors
        id: cache-vendors
        uses: actions/cache@v3
        with:
          path: code/vendor
          key: ${{runner.os}}-php-vendors
      - name: build-vendor-dependencies
        if: steps.cache-vendors.outputs.cache-hit != 'true'
        run: |
          cd code
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      ## Nodejs NPM - cache
      - name: cache nodejs npm packages
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: code/node_modules
          key: ${{runner.os}}-nodejs-build
      - name: build-npm-dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          cd code
          npm install

      - name: upgrade dependencies and build distributions
        run: |
          cd code
          composer upgrade
          npm upgrade
          npm run build

      # Copy configuration files
      - name: Copy .env
        run: | 
          php -r "file_exists('.env') || copy('./configuration/.env.example', './code/.env');"
      - name: Generate key
        run: |
          cd code 
          php artisan key:generate
      - name: Directory Permissions
        run: |
          cd code
          chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          cp configuration/phpunit.xml code/phpunit.xml
          cd code
          php vendor/bin/phpunit
