name: Laravel Testing

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "testing", "development" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      # Setup of PHP
      - uses: shivammathur/setup-php@2
        with:
          php-version: '8.1'
          extensions: oci8, BCMath, ctype, fileinfo, \
            JSON, XML, Mbstring, OpenSSL, \
            pdo, tokenizer
          tools: composer, phpunit, pecl, phpize,

      - uses: actions/checkout@v3
      # Build & install node js packages and PHP
      - name: build-dependencies
        run: |
          cd code
          npm install
          npm run build
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # Copy configuration files
      - name: Copy .env
        run: | 
          php -r "file_exists('.env') || copy('./configuration/.env.example', './code/.env');"
      - name: Generate key
        run: |
          cd code 
          php artisan key:generate
      - name: Directory Permissions
        run: |
          cd code
          chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          cp configuration/phpunit.xml code/phpunit.xml
          cd code
          php vendor/bin/phpunit
